//import shade
buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.github.johnrengelman:shadow:8.1.1'
    }
}

plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.5'
    id 'io.spring.dependency-management' version '1.1.4'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'me.loopbreak'
version = '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = '17'
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url 'https://repo.spring.io/milestone' }
    maven {
        name = "scorerepo"
        url = "https://www.cs.mcgill.ca/~joerg/maven2/"
    }
    maven {
        name = "jitpack"
        url = "https://jitpack.io"
    }
}

ext {
    set('springAiVersion', "0.8.1")
}

dependencies {
    implementation files('libs/PumlToCore-1.0-SNAPSHOT.jar')

    implementation files('libs/ClassdiagramGrader-jar-with-dependencies.jar') {
        filter {
            exclude 'org/slf4j/**'
        }
    }

    implementation('org.antlr:antlr4-runtime:4.5') {
        version {
            strictly '4.5'
        }
    }
    implementation('org.antlr:antlr4:4.5') {
        version {
            strictly '4.5'
        }
    }
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'

    implementation 'org.springframework.ai:spring-ai-vertex-ai-gemini'
    implementation 'org.springframework.ai:spring-ai-mistral-ai'
    implementation 'org.springframework.ai:spring-ai-huggingface'
    implementation 'org.springframework.ai:spring-ai-ollama'
    implementation 'org.springframework.ai:spring-ai-openai'

    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    implementation 'org.jetbrains:annotations:24.0.0'

    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    developmentOnly 'org.springframework.boot:spring-boot-docker-compose'
    runtimeOnly 'com.h2database:h2'
    runtimeOnly 'com.mysql:mysql-connector-j'
    runtimeOnly 'org.postgresql:postgresql'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

}

dependencyManagement {
    imports {
        mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
    }
}


// disable test task


tasks.named('test') {
    enabled = false
    useJUnitPlatform()
}


//project.tasks.assemble {
//    dependsOn(project.tasks.shadowJar)
////    dependsOn(reobfJar)
//}
//import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
//
//tasks.named('shadowJar', ShadowJar) {
//    minimize()
//    enableRelocation true
//    relocationPrefix "me.loopbreak.firetags.libs"
//}