name: 'hermesanalyzer-backend'
services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=hermesanalyzer'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=default_user'
    ports:
      - '3307:3306'
    volumes:
      - 'mysql-data:/var/lib/mysql'
  backend:
    image: 'hermesanalyzer/backend:latest'
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - '.env.docker'
    ports:
      - '8080:8080'
#    networks:
#        - hermesanalyzer-backend-network

volumes:
  mysql-data:
#networks:
#  hermesanalyzer-backend-network:
#    driver: bridge