name: 'hermesanalyzer-backend'
services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3307:3306'
    volumes:
      - 'mysql-data:/var/lib/mysql'
#    networks:
#        - hermesanalyzer-backend-network

volumes:
  mysql-data:
#networks:
#  hermesanalyzer-backend-network:
#    driver: bridge